### ISSUE TITLE
[비로그인 소셜 연동] 비로그인 상태에서 카카오 계정 연동시 중간에 끊으면 무한 새로 고침 현상

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#113]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

- 비로그인 상태에서 카카오 계정 연동시, "이미 가입한 계정이 있습니다~" 에서 취소시, 무한 새로 고침 현상 발생

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: 3.4.0 (36)
- 디바이스: iphone 13 mini

**Comment by seungh0** [comment]
회원가입시에도 동일한 이슈 존재하네요

**Comment by Hyunsik-Yoo** [comment]
https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/pull/117 여기서 수정되었습니당! 다음 정기배포때 확인하실 수 있어요!
