### ISSUE TITLE
[홈 주변 가게 조회] 가게 홈 메인에서 "사장님 가게"가 노출되지 않음.

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#114]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

- 액세스 로그로 봤을떄, 사장님 가게가 API 호출은 정상적으로 호출되서, 응답이 나가는거 같은데, 화면에 안보이는거 같네요

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: 3.4.0 (36)
- 디바이스: iphone 13 mini

## 예상되는 원인이 있으면 적어주세요.

- 응답 모델 깨지나요?

**Comment by Hyunsik-Yoo** [comment]
4.0.0(53)에서 수정되었습니다~!
또 발생하면 재오픈해주세요!
