### ISSUE TITLE
[회원가입] 마수신에서 뒤로가기시 앱 정지가 됩니다

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#116]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/58c4e238-c5d1-421a-8f38-90aa2bf777c6

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v3.4.0(38)
- 디바이스:

**Comment by Hyunsik-Yoo** [comment]
이 내용은 4.0.0(59) 버전에서 해결했습니다! 재발하면 다시 열어주세요~!
