### ISSUE TITLE
[투표] 투표 댓글 신고시, 블라인드 처리가 바로 안됩니다

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#131]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/8cc10a99-2d38-4704-aa4e-f8729a03342c

- 추가적으로 에러 발생시, 전반적으로 에러 메시지가 노출되도록 해야할거 같습니다

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v4.0.0 (52)
- 디바이스:

**Comment by Haccoon** [comment]
https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/pull/135 에서 수정되었습니다.
