### ISSUE TITLE
[투표 댓글] 투표 상세 진입 처음에 댓글 추가하면 카운트가 안늘어남

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#132]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

- 마이너한대, 신기해서 공유드립니다 ㅎ

https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/b3820892-8895-4619-a93e-0b6ecf225e45

- 투표 페이지 접근 후 첫 댓글 추가시에는 카운트가 안 늘어나고, 이후부터는 늘어나네여

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v4.0.0(52)
- 디바이스:

**Comment by Haccoon** [comment]
https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/pull/135 에서 수정되었습니다.
