### ISSUE TITLE
[가게 등록/수정] 영업일 취소 후 상세 화면 이동시 반영 안됨

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#138]
- 영업일 취소 후, 상세 화면 이동시 반영 안되어 있습니다

https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/ccd09aa3-a80a-4d59-bc72-f901dd81b7fd

**Comment by Hyunsik-Yoo** [comment]
v4.0.0(61) 버전에서 수정되었습니다.
