### ISSUE TITLE
[가게 상세] 방문 인증 많아지면 화면 깨짐

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#139]
https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/1fd32e28-e5cd-43aa-b33d-7b6871f545e6

**Comment by Hyunsik-Yoo** [comment]
v4.0.0(61) 버전에서 수정되었습니다.
