### ISSUE TITLE
[가게 등록/수정] 메뉴를 2번째 부터 등록하면 2배씩 늘어남

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#140]
https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/fcd509e7-c116-438b-8013-cea4f784e76e

**Comment by Hyunsik-Yoo** [comment]
v4.0.0(61) 버전에서 수정되었습니다.
