### ISSUE TITLE
[리스트 뷰] 리스트 뷰에서 탭 왔다갔다하면 화면 사라짐 

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#141]
https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/6e87691b-b82d-44b5-9501-f05211dd02b7

**Comment by Hyunsik-Yoo** [comment]
이 내용은 4.0.0(59) 버전에서 해결했습니다! 재발하면 다시 열어주세요~!

리스트뷰 화면 컨텍스트를 탭 이동할 때 가지고 있기 어려워서, 탭 이동 시 홈 화면은 내려가도록 했습니다!
