### ISSUE TITLE
[가게 리뷰 신고] 신고 화면 갔다가 다시 신고 누르면 화면 안보임

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#142]

**Comment by seungh0** [comment]
https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/51957e9e-846d-4aec-946d-02a3083b4b70

**Comment by Hyunsik-Yoo** [comment]
이거는 제 단말기에서는 발생하지 않는듯한데 어떤 상황에서 발생하셨나요!?

**Comment by seungh0** [comment]
@Hyunsik-Yoo 지금보니 내가 쓴 리뷰 신고하려할때 발생한 이슈였네요.
그쪽 이슈가 수정되면 같이 해결될거 같아요

**Comment by seungh0** [comment]
수정 확인 완료했습니다!
