### ISSUE TITLE
[스플래시 광고] 광고 버튼 이름

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#144]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

![IMG_2393](https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/d492ea53-afcd-4249-8363-2530bec2d05c)

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: 
- 디바이스:

**Comment by Hyunsik-Yoo** [comment]
이 내용은 4.0.0(59) 버전에서 해결했습니다! 재발하면 다시 열어주세요~!
