### ISSUE TITLE
[커뮤니티 & 사장님 가게] 버그 이슈 공유

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#145]
### 커뮤니티 - 투표
- [x] 투표 등록 화면에서, 1일 1회” 에서 1회도 서버에서 가져온 값으로 가능할까요? (동적으로 관리하면 좋을거 같아서요)
- [x] 신고 (기타 의견)에서 두 번 이상 신고시, 에러 메시지가 노출되지 않습니다 (뒤로 묻히는거 같아요)
- [x] 혹시 투표 상세 페이지에 딥링크 생성이 가능할까요? (푸시용) (공수가 든다면, 나중에 부탁드리겠습니다!)

### 커뮤니티 - 랭킹
- [x] (혹시나 해서) 동네 가게 랭킹에서 군포(TEST) 제외되어야 할거 같습니다 ㅎㅎ
- [x] 사장님 가게인 경우, 가게로 이동되어지지 않는 것 같습니다

### 공통
- [x] 서버 에러 발생시, 서버에서 내려주는 에러 메시지가 노출되어야 할거 같습니다
  - 사장님 가게 피드백 2회 등록 및 투표 신고 2회 시

### 사장님 가게 (상세)
- [x] 사장님 한마디가 노출 안되는거 같습니다
- [x] 즐겨찾기/공유하기 안됨 (유저 가게랑 동일)
- [x] 가게가 오픈 중인데, 하단에 “지금은 준비중”이에요가 노출되고 있습니다
- [x] 가게 리스트 뷰에서, 사장님 가게 클릭시 상세 페이지로 이동 하지 않습니다

필요하신 영상 등이 필요하시면 말씀해주세요!

**Comment by Hyunsik-Yoo** [comment]
> (혹시나 해서) 동네 가게 랭킹에서 군포(TEST) 제외되어야 할거 같습니다 ㅎㅎ 
이거는 확인해보니 개발 빌드일 경우에만 나오도록 설정되어있네요! 상용에서는 안나올겁니다!

**Comment by Haccoon** [comment]
투표 상세 딥링크 스펙 추가했습니다! 

https://www.notion.so/APP-c5eb64dbdacb4460bd2c36a519acdef7

**Comment by seungh0** [comment]
@Haccoon 투표 상세쪽 딥링크 확인 완료했습니다~
커뮤니티 탭 쪽 링크는 이동 안하는것 같습니다 (현재 따로 사용하고 있는 곳은 없습니다~)
