### ISSUE TITLE
[가게 상세/신고 더보기] 내가 쓴 리뷰에 신고 표기가 됩니다

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#149]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/31da2cdc-bdf0-4f37-97b4-61f5961eeeb8

- 한번 픽스된 이슈였던거 같은데, 또 발생하네오

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: 
- 디바이스:

**Comment by seungh0** [comment]
서버에서 내려오는 isOwner 필드로 필터링해도 좋을거 같습니다!

**Comment by Hyunsik-Yoo** [comment]
헐 isOwner가 있는지 몰랐어요..

**Comment by seungh0** [comment]
확인 완료했습니다!

**Comment by seungh0** [comment]
@Hyunsik-Yoo 신고 목록 화면에서 동일한 이슈가 있어서 재 오픈하였습니다

**Comment by seungh0** [comment]
확인 완료헀습니다~
