### ISSUE TITLE
[마이페이지] [CS] 로그아웃/회원 탈퇴시 간혹가다 Kakao SDK 에러 발생

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#150]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

![IMG_2445](https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/2806fa5a-b094-40b7-bb27-eca0e6d57f3b)

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: 
- 디바이스:

**Comment by Hyunsik-Yoo** [comment]
요것도 마지막 버전인 67버전에서 수정했습니다!
원인은 카카오톡 자체 토큰이 expire되었을 때 처리가 안되서 발생하는 오류였습니다!

**Comment by seungh0** [comment]
아하아~ 고생하셨습니다
