### ISSUE TITLE
[아이콘] 버그라고 하기엔..

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#160]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

![IMG_2482](https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/1b0f2add-f744-4641-8b2c-912503d94519)

- 여기서 기존 아이콘이 보이네여

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: 
- 디바이스:

**Comment by Hyunsik-Yoo** [comment]
엇 요거는 OS에 남아있는 앱 아이콘 캐시일겁니다! 시간 지나면 바뀔거에요!

**Comment by seungh0** [comment]
os 캐시군여 감사합니다!
