### ISSUE TITLE
[가게 리스크 뷰] 리스트뷰 => 지도뷰 이동시, 체크 설정 반영 안됨

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#162]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/fc84849c-1172-4c1c-b208-c92d52e168b6

- 지도뷰 => 리스트뷰와 다르게 리스트뷰 => 지도뷰로 이동시, 선택한 설정들이 반영되지 않음.
- ex) 리스트 뷰에서 사장님 가게만 클릭 후 지도뷰로 이동시, 체크 해제 되어 있음

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v4.0.0
- 디바이스:

**Comment by Hyunsik-Yoo** [comment]
v4.0.1에서 수정되었습니다~!
