### ISSUE TITLE
[커뮤니티 투표] 투표 선택 후 뒤로 돌아오면 반영 안되어 있음

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#165]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/b11fe2d4-a307-490c-9fae-b80f96f028f5

- 투표 선택 후 뒤로 돌아오면 반영 안되어 있음
- 메인 카드 뷰도 동일한 현상 존재

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v4.0.0
- 디바이스:

**Comment by Haccoon** [comment]
@seungh0  4.0.1 (74) 버전에서 수정되었습니다!

**Comment by seungh0** [comment]
@Haccoon 지금 테플에 올라와서 봤습니다 ㅎㅎ 고생하셨습니다!
