### ISSUE TITLE
[커뮤니티 투표] 투표 선택 후 커서 페이징 이동 후 돌아오면 반영 안되어 있음

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#166]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/db25f2a7-128a-49b8-a009-60b2d58fe865

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v4.0.0
- 디바이스:

**Comment by Haccoon** [comment]
@seungh0  4.0.1 (74) 버전에서 수정되었습니다!

**Comment by seungh0** [comment]
@Haccoon 확인했습니다~ 고생하셨습니다
