### ISSUE TITLE
[커뮤니티 투표] 마감 처리 관련 문의

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#167]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

- 투표 마감이, 혹시 시간 단위는 아니고 일 단위로 마감 처리가 되나요?
  - 예를 들어서 11/28 21:00가 종료라면, 22:00에는 마감으로 표기가 안되고 11/29 00:00 부터 마감처리되는?
- 후자라면 서버에서 투표 등록시 일 단위로 종료되게 대응해도 좋을거 같아서 문의드려봅니다!

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v4.0.0
- 디바이스:

**Comment by Haccoon** [comment]
@seungh0 큰 수정은 아니라서 앱에서 우선 시간 단위로 되게끔 수정은 해놓을게요~!

**Comment by seungh0** [comment]
좋습니다~!

**Comment by Haccoon** [comment]
@seungh0  4.0.1 (74) 버전에서 수정되었습니다!

**Comment by seungh0** [comment]
@Haccoon 고생하셨습니다~
