### ISSUE TITLE
[가게 상세]  상세 조회시 깨지는 것들이 존재

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#176]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/14a34af0-1aee-4f79-a28b-cf3d7d8f1898

- 가게 상세 조회시 깨지는 것들이 존재

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v4.0.3
- 디바이스:

**Comment by Hyunsik-Yoo** [comment]
이거 혹시 깨지는 가게 id 와 이름 알려주실 수 있나요?

**Comment by seungh0** [comment]
@Hyunsik-Yoo 
https://3dollarsinhearts.slack.com/archives/C01EUAT55CJ/p1700226036469989?thread_ts=1700183965.235829&channel=C01EUAT55CJ&message_ts=1700226036.469989

요거 참고 부탁드려요~

**Comment by Hyunsik-Yoo** [comment]
StoreReviewApiResponse.contents 타입을 non-null로 디코딩해서 에러가 발생했었습니다 ㅠ 수정되어 다음 버전 배포 예정입니다!
