### ISSUE TITLE
[가게 상세] 현금 => 카드로 잘못 표기되는 버그 존재

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#178]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

![IMG_2754](https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/62c73dd4-663e-4ffb-a448-4f2239d01a63)

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v4.0.3
- 디바이스:

**Comment by Hyunsik-Yoo** [comment]
단순 타이핑 에러. 기능상으로는 현금 기능을 하고 있었습니다.
수정되어 다음버전에 배포될 예정입니다.
