### ISSUE TITLE
[가게 상세] 사장님 가게 리뷰 남기기 => SNS 변경되어야 함

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#182]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

![IMG_2842](https://github.com/3dollar-in-my-pocket/3dollars-in-my-pocket-ios/assets/48153675/e921321f-7a36-4bc2-a655-b244505c5723)

- 사장님 가게들 중, 몇몇 가게의 경우 SNS가 아니라 리뷰 아이콘이 떠있음. (리뷰 남기기 역시 동작 안하는 중)
- 가게 종류를 storeType이 아닌, 다른 값으로 구분해서 일반 가게/사장님 가게를 구분하는지 의심됨.

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v4.0.3
- 디바이스:

**Comment by Hyunsik-Yoo** [comment]
해당 이슈도 수정했습니다! 개발계는 배포중이고 4.1.0 버전에서 수정될 예정입니다.
