### ISSUE TITLE
[가게 상세화면] Placeholder 사진을 누르면 크래시가 발생합니다.

### ISSUE THREAD

**Issue by Hyunsik-Yoo** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#31]
## 현상을 적어주세요.🐛
가게 사진이 없는 가게의 상세 화면에서 Placeholder 사진을 누르면 크래시가 발생합니다.

https://user-images.githubusercontent.com/7058293/197203447-e4e295e7-ac29-49f2-989d-97deb78b4838.MP4

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v3.0.3
- 디바이스: iPhone 12Pro Max

## 예상되는 원인이 있으면 적어주세요.
- 플레이스 홀더 선택 시, State에 있는 Image의 index를 검사하지 않고 바로 조죄하여 Out of Index 에러가 발생하는 것으로 예상됩니다.

**Comment by seungh0** [comment]
추가로 사진 4개 넘어가서 더보기로 봐야할때도 버그 있습니다.
