### ISSUE TITLE
[가게 상세 화면] (일시적으로) 삭제된 가게 접근시 다음과 같은 에러가 발생합니다

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#48]
## 현상을 적어주세요.🐛 (이해하기 쉽게 영상도 첨부해주시면 더 좋습니다.)

<img width="363" alt="image" src="https://user-images.githubusercontent.com/48153675/200166972-49ff7503-934a-4ceb-b9f1-2eb2b5d7edf7.png">

- 주변 가게가 N개 조회되어 있는 상황에, 특정 가게가 삭제되면 해당 가게에 접근하는 경우 다음과 같은 에러가 발생합니다

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v3.0.5
- 디바이스: iPhone 13 Mini

## 예상되는 원인이 있으면 적어주세요.

- 가게 상세 화면 이동시 404 에러 핸들링 필요할 것 같습니다

**Comment by Hyunsik-Yoo** [comment]
404 에러와 NF002코드를 확인하여 가게가 없는 에러 발생시에는 알럿을 message로 띄우고 확인 버튼 터치 시, 뒤로가기 되도록 수정했습니다.
